# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 13:45
from __future__ import unicode_literals

from django.db import migrations
def initial_stations(apps, schema_editor):
    Station = apps.get_model('weather', 'Station')
    Station(Region=u'新竹', Regional_Drought_Stage=[u'黃燈',u'黃燈',u'黃燈',u'黃燈',u'黃燈',u'黃燈',u'黃燈',u'黃燈',u'黃燈',u'黃燈',u'黃燈',u'黃燈'] ,Reservoir_Name='寶山+寶二', Reservoir_Storage=['2500.00','2500.00','2500.00','2500.00','2500.00','2500.00','2500.00','2500.00','2500.00','2500.00','2500.00','2500.00'] ,Reservoir_Level='250.00',Date=u'20170804').save()
    Station(Region=u'新竹', Regional_Drought_Stage=u'黃燈', Reservoir_Name=u'寶山+寶二', Reservoir_Storage='2411.00', Reservoir_Level='249.00',Date=u'20170805').save()
    Station(Region=u'台南', Regional_Drought_Stage=u'黃燈', Reservoir_Name=u'南化', Reservoir_Storage='2500.00', Reservoir_Level='250.00',Date=u'20170804').save()
    Station(Region=u'台南', Regional_Drought_Stage=u'黃燈', Reservoir_Name=u'南化', Reservoir_Storage='2413.00', Reservoir_Level='259.00',Date=u'20170805').save()

class Migration(migrations.Migration):
    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_stations),
    ]
